---
- name: Create and enable SSH tunnel service
  hosts: server_host

  tasks:
  - name: Install autossh
    become: true
    ansible.builtin.apt:
      name: autossh
      state: latest

  - name: Copy admin ssh key
    copy:
      src: ~/.ssh/admin
      dest: ~/.ssh/admin
      mode: 0600

  - name: Create systemd service file
    become: true
    copy:
      dest: /etc/systemd/system/autossh_tunnel.service
      content: |
        [Unit]
        Description=Keeps an SSH tunnel for the Minecraft server open
        After=network.target

        [Service]
        Environment="AUTOSSH_GATETIME=0"
        ExecStart=/usr/bin/autossh -fN -R 25565:localhost:25565 admin@{{ lookup('env', 'MINECRAFT_PROXY_HOST') }} -i /home/admin/.ssh/admin

        [Install]
        WantedBy=multi-user.target

  - name: Start and enable SSH tunnel service
    become: true
    systemd_service:
      name: autossh_tunnel
      state: started
      enabled: true

